<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.adobe.sign.api.WorkFlows.GetWorkflowInfoApiTest" tests="4" skipped="0" failures="1" errors="0" timestamp="2017-05-17T09:50:34" hostname="huangqixuande-MacBook-Pro.local" time="0.002">
  <properties/>
  <testcase name="testInvalidXApiUser" classname="com.adobe.sign.api.WorkFlows.GetWorkflowInfoApiTest" time="0.0"/>
  <testcase name="testGetWorkflowInfo" classname="com.adobe.sign.api.WorkFlows.GetWorkflowInfoApiTest" time="0.002">
    <failure message="java.lang.AssertionError: &quot;httpCode&quot;: 404, &quot;apiCode&quot;: INVALID_WORKFLOW_ID, &quot;message&quot;: The Workflow ID specified is invalid" type="java.lang.AssertionError">java.lang.AssertionError: &quot;httpCode&quot;: 404, &quot;apiCode&quot;: INVALID_WORKFLOW_ID, &quot;message&quot;: The Workflow ID specified is invalid
	at org.junit.Assert.fail(Assert.java:88)
	at com.adobe.sign.api.WorkFlows.GetWorkflowInfoApiTest.testGetWorkflowInfo(GetWorkflowInfoApiTest.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.adobe.sign.utils.Retry$1.evaluate(Retry.java:25)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <testcase name="testInvalidWorkflowId" classname="com.adobe.sign.api.WorkFlows.GetWorkflowInfoApiTest" time="0.0"/>
  <testcase name="testNullAndEmptyAccessToken" classname="com.adobe.sign.api.WorkFlows.GetWorkflowInfoApiTest" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[testGetWorkflowInfo(com.adobe.sign.api.WorkFlows.GetWorkflowInfoApiTest): run 1 failed
Message: "httpCode": 404, "apiCode": INVALID_WORKFLOW_ID, "message": The Workflow ID specified is invalid
testGetWorkflowInfo(com.adobe.sign.api.WorkFlows.GetWorkflowInfoApiTest): giving up after 1 failures
]]></system-err>
</testsuite>
